### ISSUE TITLE
laravel8 文件上传抛出异常 `Serialization of 'Illuminate\\Http\\UploadedFile' is not allowed`

### ISSUE THREAD

**Issue by flaravel** [Jiannei/laravel-logger#4]
![image](https://user-images.githubusercontent.com/74532850/109286012-b8578580-785c-11eb-92cd-c3e2c237fdc1.png)

**Comment by jiannei** [comment]
@flaravel  和这个扩展包没有关联。

上传的时候是否有执行异步 Job？检查下 Job  的构造函数传入的参数，改成简单的数据类型。

**Comment by flaravel** [comment]
@Jiannei 设置的是异步，在RequestHandledListener 中,$context 数组中$request->all()，包含了UploadeFile,导致在logger_async($message, $context) 中这个文件对象不能序列化

**Comment by jiannei** [comment]
> @Jiannei 设置的是异步，在RequestHandledListener 中,$context 数组中$request->all()，包含了UploadeFile,导致在logger_async($message, $context) 中这个文件对象不能序列化

大意了，后面完善下，感谢反馈~

**Comment by jiannei** [comment]
考虑当 request 中包含有 UploadedFile  时只记录文件名和文件类型信息，已修复。
