### ISSUE TITLE
装了enum就没办法装logger了

### ISSUE THREAD

**Issue by skwfar** [Jiannei/laravel-logger#5]
![image](https://user-images.githubusercontent.com/16791960/122194468-0e157380-cec8-11eb-9f44-d345c5f71854.png)
enum依赖于jiannei/helpers ^0.2.1 
但logger依赖于jiannei/helpers ^0.1.1
有冲突没有办法安装

**Comment by jiannei** [comment]
@skwfar  感谢反馈，已修复。
