### ISSUE TITLE
如何同步方式写入文件而不用队列？

### ISSUE THREAD

**Issue by Ya-hui** [Jiannei/laravel-logger#7]
我把队列 QUEUE_CONNECTION 改为database后 
始终报内存耗尽的错误

**Comment by Ya-hui** [comment]
![image](https://user-images.githubusercontent.com/13138164/133891729-ed3830f9-20d2-4c10-8adc-c7ffba86adbb.png)

**Comment by jiannei** [comment]
> 我把队列 QUEUE_CONNECTION 改为database后
> 始终报内存耗尽的错误

可以将 `QUEUE_CONNECTION` 设置为 sync，就是同步方式写文件

**Comment by Ya-hui** [comment]
但是我有其他地方 需要异步呀

**Comment by Ya-hui** [comment]
![image](https://user-images.githubusercontent.com/13138164/133893454-c2885cef-a209-424d-ae60-ddff0185d6d2.png)

为什么 会写日志不成功呢？ 正常应该是可以写成功的呀

**Comment by jiannei** [comment]
> 但是我有其他地方 需要异步呀

这是个问题，需要允许配置日志使用的队列链接，可以提 pr 来，或者改天完善一下。

**Comment by Ya-hui** [comment]
意思是不支持database 队列？

**Comment by Ya-hui** [comment]
我大概明白了我上面为什么会循环写日志了， 当使用database队列时  打开LOG_QUERY=true  会一直执行insert操作 一直写日志  变成了一个死循环
